### PR TITLE
File structure fix

### PR DESCRIPTION
**Pull request by waseemshahwan**
- Modifications to the calendar export function
- Diversified the code into multiple files for easier editing and contribution

### CODE REVIEW

**Comment by DeadPackets** [comment]
Thank you Kanye, very cool!

**Comment by waseemshahwan** [comment]
I do not have an active calendar so I could not test the calendar exporting functions. You can pull this fork and test it locally before merging.

**Comment by DeadPackets** [comment]
Does your university use Banner as well? Why is the domain in the content matching system different?

**Comment by waseemshahwan** [comment]
I tried matching subdomain only but there is no such rule in chrome's matching syntax. I already tested the functionality with my college's banner site but most of it failed. I can look at it later for more support.

**Comment by DeadPackets** [comment]
Alright, will merge for now. Many thanks, much cool.

**Pull request merged**
